### PR TITLE
Changed the task file to use the new version of the pg jdbc driver

### PR DESCRIPTION
**Pull request by sameetn**
Also changed .gitignore

### CODE REVIEW

**Comment by cgreening** [comment]
Hey sameetn - do you have a user on npmjs? I'd like to add you as a collaborator/owner of the npm repository as I don't currently have time to update the package.

**Comment by sameetn** [comment]
I did not but I just created one...sameetn

**Comment by cgreening** [comment]
You should now be a collaborator on the npm package.

**Comment by sameetn** [comment]
Done I just published the latest version.

**Pull request merged**
